import sys
import keyboard
import time
keyboard.press_and_release('left_win+r')
time.sleep(.1)
keyboard.write('cmd')
time.sleep(.1)
keyboard.press_and_release('return')
time.sleep(.5)
keyboard.write('DIR')
time.sleep(.1)
keyboard.press_and_release('return')
time.sleep(.1)
keyboard.write('mkdir helo')
time.sleep(.4)
keyboard.press_and_release('return')
time.sleep(.4)
keyboard.write('rmdir helo')
time.sleep(.3)
keyboard.press_and_release('return')
time.sleep(.1)
keyboard.write('exit')
time.sleep(.2)
keyboard.press_and_release('return')
time.sleep(.1)
